### ISSUE TITLE
add authenticator code does not support letters

### ISSUE THREAD

**Issue by ghost** [iTaysonLab/jetisteam#9]
The **"add authenticator"** code can be received either via SMS or email. In case of SMS a numeric code is sent, and if via email - with letters, but the input field does **not support letters**.

**Comment by iTaysonLab** [comment]
sorry for the long response - thanks for reporting, will fix later

**Comment by iTaysonLab** [comment]
fixed with db4ac9f407bb15eefc62511d12e54ffc3e506682
